### ISSUE TITLE
use fpr functions vs custom kable/kableExtra and at_trim_xlsheet

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/safety_plan_peace_2024#5]
fpr::fpr_sheet_trim() vs at_trim_xlsheet

fpr_kable vs kable (not going to bother with this one as short on time but may as well update in the future since sometimes known issues can be avoided with function )

**Comment by lucy-schick** [comment]
I'll make sure do use this in the next one, thanks!
